name: SilentCamera
description: "나만의 무음 카메라"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  flutter_image_gallery_saver: ^0.0.2
  # image_gallery_saver: ^1.7.1
  permission_handler: ^11.0.1
  # device_info_plus: ^8.0.0
  photo_manager: ^3.6.4
  # flutter_secure_storage: ^8.0.0
  # cupertino_icons: ^1.0.8
  # image_picker: ^0.8.5+3
  # http: ^0.13.5
  # http_parser: ^4.0.2
  # path_provider: ^2.1.5
  # camera: ^0.10.6
  # audioplayers: ^5.2.1
  # permission_handler: ^11.0.0
  # flutter_svg: ^2.0.9
  # speech_to_text: ^7.0.0
  # intl: ^0.18.0
  # dio: ^5.8.0
  # flutter_chat_ui: ^1.6.12
  # flutter_chat_types: ^3.6.0
  # flutter_tts: ^3.2.2
  # web_socket_channel: ^2.4.0
  # googleapis_auth: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true