name: SilentCamera
description: "나만의 무음 카메라"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  flutter_image_gallery_saver: ^0.0.2
  permission_handler: ^11.0.1
  photo_manager: ^3.6.4
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - "assets/icon/app_icon.png"
    - "assets/splash/full_splash.png"
  uses-material-design: true


flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"